### PR TITLE
Jenkins plugin updates - pom.xml, release drafter, README and CHANGELOG

### PR DESCRIPTION
**Pull request by FarmGeek4Life**
- Update the plugin pom version and fix related build issues and warnings
- Add a release drafter workflow
- Update the README and add a CHANGELOG with the information from the old/obsolete wiki page.

### CODE REVIEW

**Comment by FarmGeek4Life** [comment]
This will not successfully build on the Jenkins CI server until PR #9 is merged.

**Comment by FarmGeek4Life** [comment]
Force-pushed to fix commit metadata (My git config somehow managed to drop my email address)

**Comment by FarmGeek4Life** [comment]
@imod @timja - could you look this change over and merge it? An extended summary of these changes:
* Add release drafter
* Add more entries to .gitignore to ignore project files and build products from other IDEs
* Re-create the Jenkins wiki information with README.md and CHANGELOG.md (support for deprecation of the Jenkins plugin wiki pages)
* Updates to pom.xml:
  * Parent POM 2.10 -> 4.13
  * jenkins.version 1.642.3 -> 2.204
  * java.level (unspecified) -> 8
  * token-macro 1.12.1 -> 2.0
  * Remove build plugins entries
* Code changes
  * Jenkins.getActiveInstance() -> Jenkins.get() (with null check if needed)
  * Add "<?jelly escape-by-default='true'?>" to all .jelly files

**Comment by imod** [comment]
@FarmGeek4Life this plugin is open for adoption, would you like to take it over?

**Comment by FarmGeek4Life** [comment]
My only real interest is in getting a good release out (since I use it), and am not interested in becoming the regular maintainer; I don't have the time to consistently maintain more than what I already have.

I did read your note, and I do understand the challenges; as it is, I end up doing just about the bare minimum on the one plugin I maintain. My main interest is keeping my Jenkins instance functional.

**Review by gbigenios — APPROVED** [review]
thanks

**Comment by timja** [comment]
> thanks

@gbigenios you probably have an invitation sitting at https://github.com/jenkinsci to accept

**Comment by gbigenios** [comment]
> 
> 
> > thanks
> 
> @gbigenios you probably have an invitation sitting at https://github.com/jenkinsci to accept

thanks for being patient with me

**Pull request merged**
